### PR TITLE
ELEC-96: Add dependencies to setup VM box builds

### PR DESCRIPTION
**Pull request by karlding**
This pull request adds files necessary to automate the process of building a base box, using Ubuntu 16.04 LTS as the base installation image. Essentially, this means we have an immutable installation process, so we should be able to run ``packer`` multiple times, and end up with a box configured exactly the same way. I've done my best to document everything in the **README** and the provisioning scripts, but if you feel things aren't clear, let me know and I'll make the changes.

For provisioning, I've decided to use [Chef](https://www.chef.io), with configuration scripts written in Ruby. In addition, I've decided to stick with bash commands, rather than purely using recipes in a more "Chef-like" solution, since I figured that not many people (on the team) know Ruby. We could still leverage the framework for provisioning scripts that Chef provides, while still allowing everyone to understand what's going on in the provisioning steps.

The changes to support USB passthrough are in the ``Vagrantfile``, so they'll be part of the ``uw-midsun/box`` repo.

I'm thinking the workflow for deploying new boxes will be something like:

1. Build new box
2. Upload box somewhere (probably [Atlas](https://www.hashicorp.com/atlas.html))
3. People clone a ``uw-midsun/box``, whose ``Vagrantfile`` is configured to clone the firmware repo once they do ``vagrant up``. If the box is uploaded to a registry, we can use the box metadata to tell ``vagrant`` there's a newer version of the box.

If we don't upload the box somewhere, then we would just distribute the box, and then people would have to do 

```shell
wget https://example.com/boxname.box
vagrant box add uw-midsun/box boxname.box
git clone https://github.com/uw-midsun/box && cd box
vagrant up
```

Instead of simply doing

```shell
git clone https://github.com/uw-midsun/box && cd box
vagrant up
```

We might even be able to set up GitHub pages to host the box..

The generated box in ``builds/`` comes preinstalled with the following:

* git
* tmux
* vim
* build-essential
* gdb
* openocd
* gcc-arm-embedded (from PPA)
* rvm
* ruby 

I've tested this on macOS (Sierra) and Ubuntu 16.04.

**Note**: The reason why I have a bunch of extra files is in order to conform with the Apache 2 license terms. I'm not sure if we need some of them, like **CHANGELOG.md** or **MAINTAINERS.md**

### CODE REVIEW

**Comment by karlding** [comment]
To make things simpler for reviewers, most of the interesting stuff happens here:

* ``scripts/``
* ``vagrant-base.json``
* ``chef/uwmidsun-cookbooks``

**Comment by karlding** [comment]
**scripts/uwmidsun/install.sh**

Oops, good catch. I should get rid of that!

We actually no longer need any of the scripts in ``scripts/uwmidsun/``, since any provisioning scripts should all be Chef recipes called in the provisioning process when ``chef-solo`` runs. Initially I had a bunch of shell scripts that bootstrapped the whole process, which is why I had that line (but it got kind of messy).

**vagrant-base.json**:5

I don't think so. It's been a while since I've had to fiddle with the boot_options when installing Ubuntu, but I believe you can't press <kbd>CTRL</kbd> + <kbd>A</kbd> to select everything. I'll try adding it to my JSON file tonight to see if it works.

**vagrant-base.json**:115

Bumped to ``1024``.

**chef/uwmidsun-cookbooks/stm32-dev/recipes**:15

Yes, this is [this one](https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa) maintained by the GCC ARM Embedded Maintainers team.

Regarding the Apache 2 license, the ``bento-ya`` [gem](https://rubygems.org/gems/bento-ya/versions/0.0.1) is released under Apache 2, which is why I was asking. I'm not too familiar with the nuances of licensing.

**Comment by karlding** [comment]
Actually, if ``bento`` is the main piece of software preventing us from using a MIT license, I'll just remove the ``bento-ya`` as a dependency and simply use vanilla Packer to avoid the whole issue. Since we're choosing to only build a base box for a VirtualBox provider (and not supporting the other possible providers like Parallels/VM Ware, etc), I don't need to pipeline the build, and I don't actually need all that extra useful functionality that ``bento`` provides.

I'll update the ``README.md`` file tonight with instructions for using Packer (and then remove the gem from the ``Gemfile`` and ``Gemfile.lock``), but essentially instead of doing

```bash
bento build --only=virtualbox-iso vagrant-base.json
```

you'll run

```bash
packer build --only=virtualbox-iso vagrant-base.json
```

Then I'll bump our ``LICENSE`` to MIT, and we should be good.

**Comment by ckitagawa** [comment]
Looks good, any chance we can rename the repo because bento isn't actually applicable anymore?

**Comment by karlding** [comment]
Updated.

**Pull request merged**
